# Generated by Django 3.1 on 2020-09-02 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20200902_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caravan',
            name='size',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
