# Generated by Django 3.1 on 2020-09-02 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0007_auto_20200902_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('current_hp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('xp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)])),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard', to='party.caravan')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='party.memberbase')),
                ('hired_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='party.avatar')),
            ],
        ),
    ]
