# Generated by Django 3.1 on 2020-09-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_crewmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guard', to='party.caravan'),
        ),
    ]
