# Generated by Django 3.1 on 2020-09-04 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0009_auto_20200902_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbase',
            name='cost',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
