# Generated by Django 3.1 on 2020-09-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_campground'),
        ('party', '0012_auto_20200904_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbase',
            name='camps',
            field=models.ManyToManyField(blank=True, related_name='mercs', to='world.Campground'),
        ),
    ]
