# Generated by Django 3.1 on 2020-09-11 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0013_memberbase_camps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='gold',
            field=models.PositiveIntegerField(default=500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)]),
        ),
    ]
