# Generated by Django 3.1 on 2020-09-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('Weapon', 'Weapon'), ('Material', 'Material'), ('Transport', 'Transport')], default='Weapon', max_length=10),
        ),
    ]
